# Generated by Django 2.2 on 2019-10-13 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('phone', models.CharField(max_length=13)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Role')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
