# Generated by Django 2.2.5 on 2019-10-15 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Auction_Status',
            },
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=3000)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('deadline', models.DateTimeField()),
                ('created_date', models.DateTimeField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Auction_Status')),
            ],
            options={
                'db_table': 'Auction',
            },
        ),
    ]
