# Generated by Django 2.2.5 on 2019-10-19 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction_Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=3000)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
            options={
                'db_table': 'Auction_Temp',
            },
        ),
    ]
